contrato/urls.py
from django.urls import path
from .views import ContratoCreateView, ContratoUpdateView, ContratoDeleteView, ContratoListView, planes_pago, generar_plan_pago

urlpatterns = [
    path('update/<int:pk>/',
         ContratoUpdateView.as_view(), name='contrato-update'),
    path('delete/<int:pk>/',
         ContratoDeleteView.as_view(), name='contrato-delete'),
    path('list/', ContratoListView.as_view(), name='contrato-list'),
    path('create/', ContratoCreateView.as_view(), name='contrato-create'),
]

santamaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from contrato.views import planes_pago, generar_plan_pago
from django.views.generic import RedirectView


class AseguradoRedirect(RedirectView):
    permanent = False
    query_string = True
    pattern_name = 'asegurado-list'


urlpatterns = [
    path('generar-plan/<int:pk>/', generar_plan_pago, name='generar-plan'),
    path('plan-pago/', planes_pago, name='plan-pago'),
    path('admin/', admin.site.urls),
    path('asegurado/', include('asegurado.urls')),
    path('contrato/', include('contrato.urls')),
    path('', AseguradoRedirect.as_view(), name='index'),
]


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

contrato/models.py
from django.db import models

# Create your models here.


class Contrato(models.Model):
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField()
    precio_seguro = models.DecimalField(max_digits=18, decimal_places=2)
    precio_dependiente = models.DecimalField(max_digits=18, decimal_places=2)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    estado = models.IntegerField()

    def __str__(self) -> str:
        return self.titulo


class PlanPago(models.Model):
    fecha_vencimiento = models.DateField()
    monto = models.DecimalField(
        max_digits=18,
        decimal_places=2,
    )
    contrato = models.ForeignKey(
        Contrato,
        related_name='plan_pago',
        on_delete=models.SET_NULL,
        null=True
    )

contrato/forms.py
from django import forms
from .models import Contrato

form_control = 'rounded-md outline-none px-2 py-1 ring-1 ring-neutral-300 focus:ring-blue-600 focus:ring-2'


class ContratoForm(forms.ModelForm):
    class Meta:
        model = Contrato
        fields = ('titulo', 'descripcion', 'precio_seguro',
                  'precio_dependiente', 'fecha_inicio', 'fecha_fin', 'estado',)
    
        labels = {
            'titulo': 'Título',
            'descripcion': 'Descripción',
            'precio_seguro': 'P. Seguro',
            'precio_dependiente': 'P. Dependiente',
            'fecha_inicio': 'Fecha Inicio',
            'fecha_fin': 'Fecha Fin',
            'estado': 'Estado'
        }
        
        widgets = {
            'titulo': forms.TextInput(attrs={'class': form_control}),
            'descripcion': forms.Textarea(attrs={'class': form_control, 'cols': 10, 'rows': 3}),
            'precio_seguro': forms.NumberInput(attrs={'class': form_control}),
            'precio_dependiente': forms.NumberInput(attrs={'class': form_control}),
            'fecha_inicio': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={'class': form_control, 'type': 'date'},

            ),
            'fecha_fin': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={'class': form_control, 'type': 'date'}
            ),
            'estado': forms.NumberInput(attrs={'class': form_control}),
        }

contrato/views.py
from django.http import HttpRequest
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from math import ceil
from .models import Contrato, PlanPago
from .forms import ContratoForm
from datetime import datetime

# Create your views here.


def planes_pago(request: HttpRequest):
    contrato_id = request.GET.get('contrato')
    plan_pago = PlanPago.objects.filter(contrato__id=int(contrato_id)) if contrato_id else None
    context = {
        'contratos': Contrato.objects.all(),
        'contrato_id': contrato_id,
        'plan_pago': plan_pago,
    }

    return render(request, 'contrato/planes_pago.html', context)


def generar_plan_pago(request: HttpRequest, pk: int):
    contrato = Contrato.objects.get(pk=pk)
    current_month = contrato.fecha_inicio.month
    end_month = contrato.fecha_fin.month
    fecha = datetime(contrato.fecha_inicio.year, current_month, 15)
    
    while current_month <= end_month:
        fecha = datetime(fecha.year, current_month, fecha.day)
        PlanPago.objects.create(contrato=contrato, monto=contrato.precio_seguro, fecha_vencimiento=fecha)
        current_month += 1
        
    return redirect(reverse_lazy('plan-pago') + f'?contrato={pk}')


class ContratoListView(ListView):
    model = Contrato
    template_name = 'contrato/contrato_list.html'
    context_object_name = 'contratos'


class ContratoCreateView(CreateView):
    model = Contrato
    form_class = ContratoForm
    template_name = 'contrato/contrato_form.html'
    success_url = reverse_lazy('contrato-list')


class ContratoUpdateView(UpdateView):
    model = Contrato
    form_class = ContratoForm
    template_name = 'contrato/contrato_form.html'
    success_url = reverse_lazy('contrato-list')


class ContratoDeleteView(DeleteView):
    model = Contrato
    success_url = reverse_lazy('contrato-list')

contrato/templates/contrato/contrato_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Formulario de contratos{% endblock %}

{% block content %}
<section class="p-4">
    <h2 class="text-2xl font-neutral-800 mb-5 text-center">
        Eliminar Contrato
    </h2>
    <form method="POST" enctype="multipart/form-data" class="flex flex-col w-1/2 gap-6 mx-auto">
        {% csrf_token %}
        {{ form.errors }}

        <p>Esta seguro de eliminar el "{{ object }}"?</p>
        {{ form }}

        <div class="flex gap-2">
            <a href="{% url 'contrato-list' %}"
                class="flex-1 p-2 bg-neutral-700 rounded-md text-white hover:bg-opacity-70 text-center">
                Cancelar
            </a>
            <button type="submit" class="flex-1 p-2 bg-red-600 rounded-md text-white hover:bg-opacity-70">
                Si, eliminar
            </button>
        </div>
    </form>
</section>
{% endblock %}

contrato/templates/contrato/contrato_form.html
{% extends 'base.html' %}

{% block title %}Formulario de contratos{% endblock %}

{% block content %}
<section class="p-4">
    <h2 class="text-2xl font-neutral-800 mb-5 text-center">{% if object %}Editar{% else %}Nuevo{% endif %} Contrato
    </h2>
    <form method="POST" enctype="multipart/form-data" class="flex flex-col w-1/2 gap-6 mx-auto">
        {% csrf_token %}
        {{ form.errors }}
        <div class="flex flex-col gap-1">
            <label for="">{{ form.titulo.label }}</label>
            {{ form.titulo }}
        </div>

        <div class="flex flex-col gap-1">
            <label for="">{{ form.descripcion.label }}</label>
            {{ form.descripcion }}
        </div>

        <div class="flex flex-col gap-1">
            <label for="">{{ form.precio_seguro.label }}</label>
            {{ form.precio_seguro }}
        </div>

        <div class="flex flex-col gap-1">
            <label for="">{{ form.precio_dependiente.label }}</label>
            {{ form.precio_dependiente }}
        </div>

        <div class="flex flex-col gap-1">
            <label for="">{{ form.fecha_inicio.label }}</label>
            {{ form.fecha_inicio }}
        </div>

        <div class="flex flex-col gap-1">
            <label for="">{{ form.fecha_fin.label }}</label>
            {{ form.fecha_fin }}
        </div>

        <div class="flex flex-col gap-1">
            <label for="">{{ form.estado.label }}</label>
            {{ form.estado }}
        </div>

        <div class="flex gap-2">
            <a href="{% url 'contrato-list' %}"
                class="flex-1 p-2 bg-neutral-700 rounded-md text-white hover:bg-opacity-70 text-center">
                Guardar
            </a>
            <button type="submit" class="flex-1 p-2 bg-blue-600 rounded-md text-white hover:bg-opacity-70">
                Guardar
            </button>
        </div>
    </form>
</section>
{% endblock %}

contrato/templates/contrato/contrato_list.html
{% extends 'base.html' %}

{% block title %}Lista de contratos{% endblock %}

{% block content %}
<section class="p-4 flex flex-col gap-6">
    <div class="flex justify-between">
        <a href="{% url 'contrato-create' %}"
            class="p-2 rounded-md bg-blue-600 text-white uppercase text-sm font-medium hover:bg-opacity-70">
            nuevo
        </a>

        <form action="." class="flex gap-2 w-1/2">
            <input type="text"
                class="w-full px-2 ring-1 ring-neutral-300 text-sm outline-none rounded-md focus:ring-2 focus:ring-blue-500 placeholder:text-neutral-600"
                placeholder="Buscar...!">
            <button class="p-2 bg-green-600 rounded-md outline-none hover:bg-opacity-70 text-white">
                <i class="las la-search"></i>
            </button>
        </form>
    </div>

    <table class="table-auto">
        <thead>
            <tr class="text-center uppercase bg-neutral-300">
                <th>id</th>
                <th>titulo</th>
                <th>descripcion</th>
                <th>p. seguro</th>
                <th>p. dependiente</th>
                <th>inicio</th>
                <th>fin</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for contrato in contratos %}
            <tr class="text-center">
                <td>{{ contrato.id }}</td>
                <td>{{ contrato.titulo }}</td>
                <td>{{ contrato.descripcion }}</td>
                <td>{{ contrato.precio_seguro }}</td>
                <td>{{ contrato.precio_dependiente }}</td>
                <td>{{ contrato.fecha_inicio }}</td>
                <td>{{ contrato.fecha_fin }}</td>
                <td class="flex gap-2">
                    <a href="{% url 'contrato-update' contrato.pk %}"
                        class="mt-2 flex-1 p-1 bg-green-600 hover:bg-opacity-70 text-white rounded-md">
                        <i class="las la-pen la-lg"></i>
                    </a>
                    <a href="{% url 'contrato-delete' contrato.pk %}"
                        class="mt-2 flex-1 p-1 bg-red-600 hover:bg-opacity-70 text-white rounded-md">
                        <i class="las la-trash-alt la-lg"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>
{% endblock %}

contrato/templates/contrato/planes_pago.html
{% extends 'base.html' %}

{% block title %}Planes de pago{% endblock %}

{% block content %}
<section class="p-4 flex flex-col gap-6">
    <div class="flex justify-between">
        <form action="." class="flex gap-2 w-1/2">
            <select name="contrato" id="id_contrato"
            class="rounded-md outline-none px-2 py-1 ring-1 ring-neutral-300 focus:ring-blue-600 focus:ring-2">
            <option>--------</option>
            {% for contrato in contratos %}
                <option 
                    value="{{ contrato.pk }}" 
                    {% if contrato_id == contrato.pk|slugify %} selected {% endif %}
                >
                    {{contrato.titulo }}
                </option>
                {% endfor %}
            </select>
            <button type="submit" class="p-2 bg-green-600 rounded-md outline-none hover:bg-opacity-70 text-white">
                <i class="las la-search"></i>
            </button>
        </form>
    </div>

    {% if plan_pago %}
    <table class="table-auto">
        <thead>
            <tr class="text-center uppercase bg-neutral-300">
                <th>cuota</th>
                <th>fecha Vencimiento</th>
                <th>Monto</th>
            </tr>
        </thead>
        <tbody>
            {% for plan in plan_pago %}
            <tr class="text-center">
                <td class="p-2">{{ forloop.counter }}</td>
                <td class="p-2">{{ plan.fecha_vencimiento }}</td>
                <td class="p-2">{{ plan.monto }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% elif contrato_id %}
        <div>
            No se ha encontrado un plan de pago, generar uno <a href="{% url 'generar-plan' contrato_id %}" class="text-blue-600 hover:text-opacity-70">aqui.</a>
        </div>
    {% endif %}
</section>
{% endblock %}